diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -0,0 +1,45 @@
+name: Build NEOVIA
+
+on:
+  push:
+    branches: [ main, master ]
+  pull_request:
+    branches: [ main, master ]
+  release:
+    types: [created]
+
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    container: devkitpro/devkita64:latest
+    
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+      
+    - name: Install dependencies
+      run: |
+        sudo dkp-pacman -Syu --noconfirm
+        sudo dkp-pacman -S --noconfirm switch-dev switch-curl switch-jsoncpp
+        
+    - name: Build NEOVIA
+      run: |
+        export DEVKITPRO=/opt/devkitpro
+        export DEVKITARM=/opt/devkitpro/devkitARM
+        export DEVKITPPC=/opt/devkitpro/devkitPPC
+        make clean
+        make -j$(nproc)
+        
+    - name: Upload build artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: NEOVIA-nro
+        path: NEOVIA.nro
+        
+    - name: Release
+      if: github.event_name == 'release'
+      uses: softprops/action-gh-release@v1
+      with:
+        files: NEOVIA.nro
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
