name: Build NEOVIA

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    
    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo dkp-pacman -Syu --noconfirm
        sudo dkp-pacman -S --noconfirm switch-dev switch-curl
        export DEVKITPRO=/opt/devkitpro
        make
    - uses: softprops/action-gh-release@v2
      with:
        files: NEOVIA.nro
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
