name: Build NEOVIA
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        dkp-pacman -Syu --noconfirm
        dkp-pacman -S --noconfirm switch-dev switch-curl
        make clean && make -j$(nproc)
    - uses: actions/upload-artifact@v4
      with:
        name: NEOVIA-nro
        path: NEOVIA.nro
